### PR TITLE
Making library more compliant to work with VerneMQ

### PR DESCRIPTION
**Pull request by gokr**
I chatted with one of the developers of VerneMQ and he helped me diagnose why I couldn't connect to VerneMQ (but worked fine with Mosquitto or EMQTT). It turns out one must send willQos even if willFlag is set to false. I also added some defensive tweaks, like if you forget to call will() (API not so great since easy to miss) and also making sure disconnect() does not fail.

### CODE REVIEW

**Comment by shamblett** [comment]
Hi,

From the MQTT spec version 3.1.1  --

If the Will Flag is set to 0 the Will QoS and Will Retain fields in the Connect Flags MUST be set to zero
and the Will Topic and Will Message fields MUST NOT be present in the payload [MQTT-3.1.2-11].
If the Will Flag is set to 0, a Will Message MUST NOT be published when this Network Connection ends.

-----

So it looks like the VerneMQ broker is different in this respect, this is probably why Mosquito and EMQTT are OK, or its not using version 3.1.1(version 3.1 is less clear on this). Note that the client has also been tested with Googles IOT MQTT broker and IBM's Bluemix implementation. 

I'd rather not change the default behaviour of the client to break the spec, however, we should cater for these variants. I'd suggest adding a suitably named method that must be invoked on the client before connecting to instruct it to do this, or maybe add a protocol version named 'Verne' or something that supports this behaviour.

Defensive code additions are always good, I've not checked the last point yet.

**Comment by gokr** [comment]
Mmm, I haven't followed the code in super detail - but... I thought the issue was that the lib didn't send willQos, though it really should, even if willFlag is 0. So I am not sure why you wrote that "VerneMQ broker is different". Or did I do the wrong fix? I thought I made sure willQos was sent, as spec says it should be.

**Comment by shamblett** [comment]
Ah yes sorry my bad, I didn't look at the code just your commentary, I thought you meant you were setting a Qos other than atMostOnce(0) coupled with the fact I thought I initialised these fields to 0, seems I didn't

MqttClientConnectFlags does this 

----

bool willFlag = false;
MqttQos willQos = MqttQos.atLeastOnce;

----

which should of course be atMostOnce. OK, I'll merge your changes and just test the client with Googles IOT, if OK(I'm expecting it to be) I'll republish. BTW do you want adding to the authors file?

**Comment by gokr** [comment]
Ah, that fix is probably cleaner. Nah, authors not needed ;)

**Comment by shamblett** [comment]
OK, version updated to 1.8.0 and published.

**Pull request merged**
