### PR TITLE
Fix for aws iot bug

### PR DESCRIPTION
**Pull request by dedvalson**
The Amazon Web Services (AWS) IOT MQTT interface has a bug that causes it not to connect if unexpected message headers are present in the initial GET message during the handshake. Since the httpclient classes insist on adding those headers, an alternate method is used to perform the handshake. After the handshake everything goes back to the normal websocket class.

This all happens in a new file called mqtt_client_mqtt_ws**2**_connection.dart

Miminal changes to other files were made as needed to invoke the new class

This change adds a flag at the top Client level (parallel to the useWebSocket flag) called useAlternateWebSocketImplementation that causes this alternate code to be used. 

This code also fixes the flutter example code to use the current library version.

### CODE REVIEW

**Comment by shamblett** [comment]
Thanks for this, I've merged it into my development branch for now, this will be in the next release.

**Comment by shamblett** [comment]
Client republished at version 5.4.0

**Comment by dedvalson** [comment]
So after a finding out further information I think this whole thing was unnecessary. It turns out that AWS is OK with the other headers, it is simply that if the URL includes the port number (like :443) the host header must also include it. This is technically incorrect on the part of AWS but is more easily worked around by simply leaving the :443 off of the URL.

**Comment by shamblett** [comment]
OK, so there is a more elegant solution than the one we have but the one we have works, to remove the port from the url string would need a client update anyway so I'm OK with leaving things as they are for now, maybe in the future we could use the alternate ws flag to remove the port from the url string this way the user would see no functional change but I don't think this is a priority

**Pull request merged**
