### PR TITLE
feat: unsubscribing example improvement

### PR DESCRIPTION
**Pull request by boborua**
#506

Also, is it possible to changing client's api `subscribe` to:
```
typedef OnDataCallback = void Function(List<MqttReceivedMessage<MqttMessage?>> c);

class MqttClient {
  // ---
  Subscription? subscribe(String topic, MqttQos qosLevel);
  // +++
  Subscription? subscribe(String topic, MqttQos qosLevel, [OnDataCallback cb]);
}
```

### CODE REVIEW

**Comment by shamblett** [comment]
OK I need to think about this a bit, I'd rather not have the user remember to do this, it's a cleanup that's needed on disconnect, so I'd rather have it in the disconnect() method if possible. It does need to be done though.

**Comment by boborua** [comment]
> OK I need to think about this a bit, I'd rather not have the user remember to do this, it's a cleanup that's needed on disconnect, so I'd rather have it in the disconnect() method if possible. It does need to be done though.

I see.
In current usage of subscribing/unsbuscribing, the callback attached to `client.updates` should be a message dispatcher?
 If there are two topics, `client.updates.listen` should only be invoked once?

**Comment by boborua** [comment]
In our scenario , it's very common that we subscribe to `topicA` when user going to `PageA`, then we unsubscirbe `topicA` as user leave `PageA`. Later, we subscribe/unsubscribe to `topicB` as user enter/leave `PageB`.

So, the cleanup of `client.updates` seems needing to be done when unsubscribing other than `disconnecting`.

**Comment by boborua** [comment]
> In our scenario , it's very common that we subscribe to `topicA` when user going to `PageA`, then we unsubscirbe `topicA` as user leave `PageA`. Later, we subscribe/unsubscribe to `topicB` as user enter/leave `PageB`.
> 
> So, the cleanup of `client.updates` seems needing to be done when unsubscribing other than `disconnecting`.

Let me to be more detailed,
As there's no specific documentation, in our previous usage:
1. init client
2. `client.subscirbe('topicA', MqttQos.atLeastOnce)`
3. `client.updates.listen((c) => print('topicA: $c'))`
4. `client.unsubscirbe('topicA')`
5. `client.subscirbe('topicB', MqttQos.atLeastOnce)`
6. `client.updates.listen((c) => print('topicB: $c'))`
7. `client.unsubscirbe('topicA')`

So, even though we'll not receive message from `topicA`, but when message from `topicB` comes, we'll get **two** message callback.

**Comment by shamblett** [comment]
OK I see what you are doing, you don't need to listen twice, you only need to listen once as it listens to messages from all subscriptions not just ones you subscribe to before you start listening, your sequence should be -

Connect
Listen
Subscribe to topics a,b,c
You will now get messages for topics a, b and c
Unsubscribe topic a
You will now get messages for topics b and c - no need to listen again.
Subscribe topic d
You will now get messages for topics b,c and d - no need to listen again.
Disconnect.

In your use case you do need to cancel your first listen before you listen again. 

This however is not a general purpose use case, most users just listen once and subscribe/unsubscribe as they wish.
See the API docs for the client updates getter -
```
/// The stream on which all subscribed topic updates are published to
  Stream<List<MqttReceivedMessage<MqttMessage>>>? get updates =>
      subscriptionsManager?.subscriptionNotifier;
```
Notice it says 'all' subscribed topics.

The examples are slightly misleading here in that they show subscription before listening, I will update these to reverse this to make it clearer if you think it would be better but you are the first to raise this so I guess it must be clear to all the other users.

Looking at the disconnect() method we don't seem to explicitly cancel the updates stream, I think this should be added,  I'll do this also.

**Comment by boborua** [comment]
Ok, it seems we can close this PR. now ?

**Pull request closed without merging**
