### PR TITLE
[refactor] dynamic type removal

### PR DESCRIPTION
**Pull request by aaassseee**
removed dynamic type to prevent getting parameter and calling function with nullable or wrong type crashs.

### CODE REVIEW

**Comment by aaassseee** [comment]
@shamblett Please feel free to take a full review and test with refactoring dynamic type

**Comment by aaassseee** [comment]
I am not sure everything is working because I don't have an AWS or Google IoT MQTT account

**Comment by shamblett** [comment]
OK I've created a branch for this for now. Question, what is this actually for? You mention 'with nullable or wrong type crashs.' above, what logs do you have of these crashes? What circumstances cause them?

**Comment by aaassseee** [comment]
## Goal
This pull request helps on preventing getting values and calling function on anonymous type.

## Motivation
The first problem I am facing with the anonymous type is in mqtt_client_mqtt_server_connection.dart line 95 client?.add
https://github.com/shamblett/mqtt_client/blob/3aff27474350ab0942091981fa69048f0837741b/lib/src/connectionhandling/server/mqtt_client_mqtt_server_connection.dart#L93-L96
Due to issue #377, I am in the process of digging into code to find out what are causes the issue. Then I found there is a client which is a dynamic type object calling add function.  Calling function with dynamic type without casting the object it seems a big red flag to me. First it is hard to maintain the code without any information, for example developers didn't know which class call the add function and lacking information about the object is nullable or not. Second calling function without bounding any type with it may causing crash when the application in runtime level. In https://github.com/shamblett/mqtt_client/blob/3dc544fa55bbb13c5cfa5a0d1aa5d04334d9073a/lib/src/mqtt_client_topic.dart#L15-L21
we can find topic is accepting a list of dynamic object call validations and  somehow calling the validation one by one in line 18 to 20. If a non Function type is getting injected to the validation list. There are no ways to tell developers you are injecting wrong type to the constructor and this may cause hidden errors through the development in the future.

Last but not least, eliminating most of the dynamic type can helps on more readable code. In https://github.com/shamblett/mqtt_client/blob/3dc544fa55bbb13c5cfa5a0d1aa5d04334d9073a/lib/src/mqtt_client.dart#L76
we can see connectionHandler is a dynamic type. When I was trying to make it as MqttConnectionHandlerBase? something wrong is happening. From https://github.com/shamblett/mqtt_client/blob/3dc544fa55bbb13c5cfa5a0d1aa5d04334d9073a/lib/src/mqtt_client.dart#L230-L238
the analyzer start giving red line errors about the connectionHandler maybe null when setting parameters into the connectionHandler. I don't know is there a case calling connect with a null connectionHandler. However, removing the dynamic types actually let the dart analyzer warns you about error may happens in some situation.

**Comment by shamblett** [comment]
Yes OK, when it first came out back in 2012/13 I think, Google pushed Dart as a 'dynamic' language but seemingly ever since then have slowly been turning it more into a statically typed language(generics, null aware etc.) probably because of the impact of flutter so I have no problem in moving in this direction, especially if it aids maintenance and fault finding.

My concern of course is by doing this we don't introduce some subtlety that will trip up users. I'll do my testing and see what comes up.

**Comment by shamblett** [comment]
OK, finished my testing, looks OK to me, this and #388 merged into master, package re released at version 9.6.9

**Pull request merged**
