### PR TITLE
fixing #377

### PR DESCRIPTION
**Pull request by aaassseee**
rough idea about fixing #377

### CODE REVIEW

**Comment by aaassseee** [comment]
I made the pull request ready to review. If you need to cover all sendMessage function with this solution, I can still help within this pull request.

**Comment by shamblett** [comment]
Its Ok as it is, lets go with what we have now initially.

**Comment by shamblett** [comment]
Hi, you have a formatting error, please dartfmt your code,  thanks.

**Comment by aaassseee** [comment]
@shamblett done

**Pull request merged**
